language: cpp
depth: 3

matrix:
 include:
  - os: linux
    dist: trusty
    sudo: true
    compiler: gcc
    env:
     - QT_REPO="ppa:beineri/opt-qt551-trusty"
     - QT_VERSION="qt55"
  - os: linux
    dist: trusty
    sudo: true
    compiler: gcc
    env:
     - QT_REPO="ppa:beineri/opt-qt562-trusty"
     - QT_VERSION="qt56"
  - os: linux
    dist: trusty
    sudo: true
    compiler: gcc
    env:
     - QT_REPO="ppa:beineri/opt-qt571-trusty"
     - QT_VERSION="qt57"
  - os: linux
    dist: trusty
    sudo: true
    compiler: gcc
    env:
     - QT_REPO="ppa:beineri/opt-qt58-trusty"
     - QT_VERSION="qt58"
  - os: linux
    dist: trusty
    sudo: true
    compiler: gcc
    env:
     - QT_REPO="ppa:beineri/opt-qt592-trusty"
     - QT_VERSION="qt59"
     
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
         sudo add-apt-repository "$QT_REPO" -y;
         sudo apt-get update -qq;
         sudo apt-get install -qq ${QT_VERSION}base ${QT_VERSION}translations ${QT_VERSION}tools;
         sudo apt-get install -qq libsqlite3-dev libzip-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libuchardet-dev libgl1-mesa-dev;
         git clone https://github.com/datasift/libcld2; pushd libcld2 && make && sudo make install; popd;
    fi

install:
  - find /opt -name "qt*-env.sh";
  - source /opt/${QT_VERSION}/bin/${QT_VERSION}-env.sh;
  - export QTHOME=/opt/$QT_VERSION;

script:
  - qmake -r
  - make
